server:
  port: ${CUSTOM.SERVER.PORT:8088}

# Eureka Client Config
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 05e7a8bb71ab6f87bbce
            client-secret: a66498c3fee0f47ca89f64e31081778c1a2ba459
          # google:
          #  client-id: 905303725226-mmplrnc3kk333qjcqokkcatuses2r2b0.apps.googleusercontent.com
          #  client-secret: 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
